name: run
on:
  push: {}
  workflow_dispatch: 
    inputs:
      org_or_user:
        description: 'The org (or user) to calculate total lines of code'
        required: false
        type: string
jobs:
  run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: script/bootstrap
        run: script/bootstrap
      
      - name: count workflow dispatch
        if: github.event_name == 'workflow_dispatch'
        run: script/count ${{ inputs.org_or_user }}

      - name: default count
        if: github.event_name != 'workflow_dispatch'
        run: script/count balter-test-org
